import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
import {NavbarCustom} from '../components/NavbarCustom'
import React, {useState, useEffect} from 'react'
import pokemonService from '../services/pokemon'
import { CardCustom } from '../components/CardCustom'


export default function Home() {
  const [nombrePokemon, setNombrePokemon] = useState([])
  useEffect(() => {
    const getPokemones = async() => {
      try {
        const pokemonResult = await pokemonService.getPokemones()
        setNombrePokemon(pokemonResult.results)
        console.log(pokemonResult)
      } catch (error) {
        console.log('error', error)
      }
    }
    getPokemones()
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavbarCustom/>
      </header>
      <main className={`${styles.main} ${styles.mainBg}`}> 
        <Link href='/pokemon-list'>
          <button >go to pokemon list</button>
        </Link>
        {
         nombrePokemon.map((pokemon, index) => (
           <div key={index}>
             <CardCustom pokemon={pokemon}/>
           </div>
         ))
        }
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
